//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarmas
    {
        public int IdAlarma { get; set; }
        public int IdRelevamiento { get; set; }
        public int IdUmbral { get; set; }
        public string Tipo { get; set; }
        public string Observaciones { get; set; }
        public long Cantidad { get; set; }
        public int IdInsecto { get; set; }
        public long ValorMaximo { get; set; }
        public int IdProvincia { get; set; }
        public int IdMes { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Relevamientos Relevamientos { get; set; }
        public virtual Umbrales Umbrales { get; set; }
        public virtual Insectos Insectos { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
