//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HalconDBEntities : DbContext
    {
        public HalconDBEntities()
            : base("name=HalconDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarmas> Alarmas { get; set; }
        public virtual DbSet<Campos> Campos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Insectos> Insectos { get; set; }
        public virtual DbSet<Lecturas> Lecturas { get; set; }
        public virtual DbSet<LecturasManuales> LecturasManuales { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Mantenimientos> Mantenimientos { get; set; }
        public virtual DbSet<Monitoreos> Monitoreos { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Relevamientos> Relevamientos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
        public virtual DbSet<Trampas> Trampas { get; set; }
        public virtual DbSet<Umbrales> Umbrales { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
