//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campos()
        {
            this.Trampas = new HashSet<Trampas>();
        }
    
        public int IdCampo { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public System.Data.Entity.Spatial.DbGeography LatLong { get; set; }
        public int IdEstado { get; set; }
        public int IdCliente { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Localidades Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trampas> Trampas { get; set; }
    }
}
