//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insectos()
        {
            this.Lecturas = new HashSet<Lecturas>();
        }
    
        public int IdInsecto { get; set; }
        public string NombreCientifico { get; set; }
        public string NombreVulgar { get; set; }
        public int IdGenero { get; set; }
        public Nullable<int> Ancho { get; set; }
        public Nullable<int> Largo { get; set; }
        public Nullable<double> FrecuenciaMin { get; set; }
        public Nullable<double> FrecuenciaMax { get; set; }
        public int IdEstado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Generos Generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecturas> Lecturas { get; set; }
    }
}
