//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturas
    {
        public int IdLectura { get; set; }
        public int IdMonitoreo { get; set; }
        public int Frecuencia { get; set; }
        public int Volumen { get; set; }
        public Nullable<int> IdInsecto { get; set; }
        public int IdEstado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Insectos Insectos { get; set; }
        public virtual Monitoreos Monitoreos { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
