//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimientos
    {
        public long IdMantenimiento { get; set; }
        public int IdTrampa { get; set; }
        public int IdUsuario { get; set; }
        public int IdTipoMantenimiento { get; set; }
        public System.DateTime FechaMantenimiento { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Trampas Trampas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
