//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoreos
    {
        public int IdMonitoreo { get; set; }
        public int IdRelevamiento { get; set; }
        public System.DateTime FechaMonitoreo { get; set; }
        public double Temperatura { get; set; }
        public double Luz { get; set; }
        public double Humedad { get; set; }
        public Nullable<double> Bateria { get; set; }
        public int IdEstado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Relevamientos Relevamientos { get; set; }
    }
}
