//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoreos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monitoreos()
        {
            this.Lecturas = new HashSet<Lecturas>();
        }
    
        public int IdMonitoreo { get; set; }
        public int IdRelevamiento { get; set; }
        public int Hora { get; set; }
        public int Temperatura { get; set; }
        public int Luz { get; set; }
        public int Humedad { get; set; }
        public int IdEstado { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecturas> Lecturas { get; set; }
        public virtual Relevamientos Relevamientos { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
