//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int IdTelefono { get; set; }
        public int IdTipoTelefono { get; set; }
        public string Numero { get; set; }
        public int IdPersona { get; set; }
        public int IdEstado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Estados Estados { get; set; }
    }
}
