//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trampas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trampas()
        {
            this.Relevamientos = new HashSet<Relevamientos>();
            this.Mantenimientos = new HashSet<Mantenimientos>();
        }
    
        public int IdTrampa { get; set; }
        public int IdCampo { get; set; }
        public int IdEstado { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> BateriaFElab { get; set; }
        public Nullable<System.DateTime> BateriaFVenc { get; set; }
    
        public virtual Campos Campos { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relevamientos> Relevamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimientos> Mantenimientos { get; set; }
    }
}
