//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umbrales
    {
        public int IdUmbral { get; set; }
        public int IdInsecto { get; set; }
        public long ValorMaximo { get; set; }
    
        public virtual Insectos Insectos { get; set; }
    }
}
